// https://fs-blog-app-backend-mongo.onrender.com/api/users
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "Random Dude",
    "name": "Careless User",
    "password": "12"
}
// password is less than 3 characters, should return 400 "error: 'invalid username or password'" (../controllers/users)