// https://fs-blog-app-backend-mongo.onrender.com/api/users
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "Fourth Dude",
    "name": "Fourth DUde",
    "password": "123456"
}